### PR TITLE
Feature/navigation fragment implementation

### PR DESCRIPTION
**Pull request by ShankarenfoPannagianiDharma**
Implement the navigation fragment to Activities Main, Rent, Host, which on clicking of tabs leads user to Rent, Host or Profile.

I'm not sure if I should add it into the profile page- that page has its own back button and Including a navigation tab might confuse the user? not sure.

I also can't find the purchase page, so that one is not functioning yet. Might need an explanation, sorry.

Tested with my own android.

Thank you for your time.

### CODE REVIEW

**Review by jasonn0118 — APPROVED** [review]
LGTM

**Comment by hy2207** [comment]
good:)

**Review by hy2207 — APPROVED** [review]

**Comment by Sangmean** [comment]
good for me too :)

**Comment by Sangmean** [comment]
and i can delete the back button that was just for ui :) since we are using fragement I think ne need for back button

**Pull request merged**
